#pragma config(Motor,  port2,           leftFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBackDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightFrontDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightBackDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           flywheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           flipper,       tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//VEX Competition Control and Duration Settings (in seconds)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

//ArcadeBot
//Built for 2018 Vex competition, "Turning Point"
//For WildStang use only
//Developed by WhiteHoodHacker

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// This is used to execute robot commands before the start of the VEX Competition.
// Modify the code to add specific robot commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, etc.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control the robot during the autonomous phase of the VEX Competition.
// Modify the code to add robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{



}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control the robot during the user control phase of the VEX Competition.
// Modify the code to add robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	//Variables for flywheel toggle button
	int flywheelToggleState = 0;
	int flywheelButtonPressed = 0;

	while (true)
	{
		//Code for arcade drive (controlled by left joystick)
		motor[leftFrontDrive] = vexRT[Ch4] + vexRT[Ch3];
		motor[leftBackDrive] = vexRT[Ch4] + vexRT[Ch3];
		motor[rightFrontDrive] = vexRT[Ch4] - vexRT[Ch3];
		motor[rightBackDrive] = vexRT[Ch4] - vexRT[Ch3];

		//Code for intake (controlled by 8D button)
		if(vexRT[Btn8D] == 1)
		{
			motor[intake] = 100;
		}
		else
		{
			motor[intake] = 0;
		}

		//Code for flywheel (controlled by 8R button)
		if(vexRT[Btn8R] == 1)
		{
			if(! flywheelButtonPressed)
			{
				flywheelToggleState = 1 - flywheelToggleState;
				flywheelButtonPressed = 1;
			}
		}
		else
		{
			flywheelButtonPressed = 0;
		}
		if(flywheelToggleState)
		{
			motor[flywheel] = 100;
		}
		else
		{
			motor[flywheel] = 0;
		}

		//Code for flipper (controlled by right joystick)
		motor[flipper] = vexRT[Ch1];
	}
}
